import styles from "./page.module.css";
import { createHand } from "./helpers/createHands";
import { Footer } from "./components/footer";
import { Header } from "./components/header";

export default function Home() {
  return (
    <div className={styles.page}>
      <div className={styles.header}>
        <Header />
      </div>

      <div className={styles.content}>
        {createHand([
          "Z5",
          "Z5",
          "Z5",
          "Z6",
          "Z6",
          "Z6",
          "Z7",
          "Z7",
          "P1",
          "P1",
          "P2",
          "P2",
          "P3",
        ])}
        {createHand([
          "S2",
          "S3",
          "S4",
          "S4",
          "S5",
          "S6",
          "M6",
          "M7",
          "M8",
          "P1",
          "P1",
          "P2",
          "P3",
        ])}
        {createHand([
          "Z5",
          "Z5",
          "Z5",
          "Z6",
          "Z6",
          "Z6",
          "Z7",
          "Z7",
          "P1",
          "P1",
          "P2",
          "P2",
          "P3",
        ])}
        {createHand([
          "Z5",
          "Z5",
          "Z5",
          "Z6",
          "Z6",
          "Z6",
          "Z7",
          "Z7",
          "P1",
          "P1",
          "P2",
          "P2",
          "P3",
        ])}
        {createHand([
          "Z5",
          "Z5",
          "Z5",
          "Z6",
          "Z6",
          "Z6",
          "Z7",
          "Z7",
          "P1",
          "P1",
          "P2",
          "P2",
          "P3",
        ])}
        {createHand([
          "Z5",
          "Z5",
          "Z5",
          "Z6",
          "Z6",
          "Z6",
          "Z7",
          "Z7",
          "P1",
          "P1",
          "P2",
          "P2",
          "P3",
        ])}
        {createHand([
          "Z5",
          "Z5",
          "Z5",
          "Z6",
          "Z6",
          "Z6",
          "Z7",
          "Z7",
          "P1",
          "P1",
          "P2",
          "P2",
          "P3",
        ])}
        {createHand([
          "Z5",
          "Z5",
          "Z5",
          "Z6",
          "Z6",
          "Z6",
          "Z7",
          "Z7",
          "P1",
          "P1",
          "P2",
          "P2",
          "P3",
        ])}
        {createHand([
          "Z5",
          "Z5",
          "Z5",
          "Z6",
          "Z6",
          "Z6",
          "Z7",
          "Z7",
          "P1",
          "P1",
          "P2",
          "P2",
          "P3",
        ])}
        {createHand([
          "Z5",
          "Z5",
          "Z5",
          "Z6",
          "Z6",
          "Z6",
          "Z7",
          "Z7",
          "P1",
          "P1",
          "P2",
          "P2",
          "P3",
        ])}
        {createHand([
          "Z5",
          "Z5",
          "Z5",
          "Z6",
          "Z6",
          "Z6",
          "Z7",
          "Z7",
          "P1",
          "P1",
          "P2",
          "P2",
          "P3",
        ])}
        {createHand([
          "Z5",
          "Z5",
          "Z5",
          "Z6",
          "Z6",
          "Z6",
          "Z7",
          "Z7",
          "P1",
          "P1",
          "P2",
          "P2",
          "P3",
        ])}
        {createHand([
          "Z5",
          "Z5",
          "Z5",
          "Z6",
          "Z6",
          "Z6",
          "Z7",
          "Z7",
          "P1",
          "P1",
          "P2",
          "P2",
          "P3",
        ])}
        {createHand([
          "Z5",
          "Z5",
          "Z5",
          "Z6",
          "Z6",
          "Z6",
          "Z7",
          "Z7",
          "P1",
          "P1",
          "P2",
          "P2",
          "P3",
        ])}
        {createHand([
          "Z5",
          "Z5",
          "Z5",
          "Z6",
          "Z6",
          "Z6",
          "Z7",
          "Z7",
          "P1",
          "P1",
          "P2",
          "P2",
          "P3",
        ])}
      </div>
      <div className={styles.footer}>
        <Footer />
      </div>
    </div>
  );
}
